version: 2

jobs:
   #build:
     #...
   deploy:
     #machine:
     #  enabled: true
     steps:
       - run:
           name: Deploy Over SSH
           command: |
             ssh $SSH_USER@$SSH_HOST "touch ~/hello_from_circleci.txt"

workflows:
   version: 2
   build-and-deploy:
     jobs:
       #- build
       - deploy
           #requires:
            # - build # only deploy once build job has completed
           #filters:
             #branches:
               #only: main # only deploy on the main branch