version: 2

jobs:
    build:
      machine: true
      resource_class: arm.medium
      steps:
        - checkout
        - run:
            name: Build NextJS
            command: |
              docker build --build-arg NEXT_PUBLIC_FT_CLIENT_ID=$FT_CLIENT_ID --build-arg NEXT_PUBLIC_FT_REDIRECT_URI=$FT_REDIRECT_URI ./src/nextjs-front -t aurelienbrabant/transcendance_front
        - run:
            name: Build NestJS
            command: |
              docker build ./src/nestjs-back -t aurelienbrabant/transcendance_back
        - run:
            name: Push images to docker hub
            command: |
              echo "$DOCKERHUB_PASSWORD" | docker login --username $DOCKERHUB_LOGIN --password-stdin
              docker push aurelienbrabant/transcendance_front:latest
              docker push aurelienbrabant/transcendance_back:latest
    deploy:
      machine: true
      steps:
        - run:
            name: Deploy Over SSH
            command: |
             ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "$HOME/.local/bin/docker-compose pull && $HOME/.local/bin/docker-compose -f flamboyant_compose.yml up -d"

workflows:
   version: 2
   build-and-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build # only deploy once build job has completed
           #filters:
             #branches:
               #only: main # only deploy on the main branch